import type { Metadata } from "next";

import "./globals.css";



export const metadata: Metadata = {
  title: "Tally | Expense Tracker",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`antialiased`}
    >
      <body className="">{children}</body>
    </html>
  );
}
